<?php
define('ROOT_PATH',dirname(dirname(__DIR__)));
define('LIBRARY', ROOT_PATH.DIRECTORY_SEPARATOR.'library');
define('CONFIG_PATH',ROOT_PATH.DIRECTORY_SEPARATOR.'config');
define('YII_PATH',LIBRARY.DIRECTORY_SEPARATOR.'framework');
define('BASE_PATH',ROOT_PATH.DIRECTORY_SEPARATOR.'application');
define('WEB_PATH',ROOT_PATH.DIRECTORY_SEPARATOR.'wwwroot');
define('RESOURCE_PATH', WEB_PATH.DIRECTORY_SEPARATOR.'resources');
define('RESOURCE','resources');
define('HOME_URL','http://www.lfeel.com');
define('RESOURCE_URL', HOME_URL.DIRECTORY_SEPARATOR.'resources');
define('THEME_PATH','webroot.themes');
define('API_DELETEUSER', 1);       
define('API_RENAMEUSER', 0);       
define('API_GETTAG', 1);        
define('API_SYNLOGIN', 1);     
define('API_SYNLOGOUT', 1);     
define('API_UPDATEPW', 1);      
define('API_UPDATEBADWORDS', 1);   
define('API_UPDATEHOSTS', 1);       
define('API_UPDATEAPPS', 1);      
define('API_UPDATECLIENT', 1);      
define('API_UPDATECREDIT', 1);     
define('API_GETCREDITSETTINGS', 1);  
define('API_GETCREDIT', 1);     
define('API_UPDATECREDITSETTINGS', 1);  
  
define('API_RETURN_SUCCEED', '1');  
define('API_RETURN_FAILED', '-1');  
define('API_RETURN_FORBIDDEN', '-2');  
$yii=YII_PATH.DIRECTORY_SEPARATOR.'yiilite.php';
$config=dirname(__FILE__).BASE_PATH.'/config/main.php';
defined('YII_DEBUG') or define('YII_DEBUG',FALSE);
defined('YII_TRACE_LEVEL') or define('YII_TRACE_LEVEL',0);
$config = BASE_PATH.DIRECTORY_SEPARATOR.'config'.DIRECTORY_SEPARATOR.'main.php';
$uc_config = WEB_PATH.DIRECTORY_SEPARATOR.'api'.DIRECTORY_SEPARATOR.'UConfig.php';
include($yii);
include_once($uc_config);
require(BASE_PATH.DIRECTORY_SEPARATOR.'components'.DIRECTORY_SEPARATOR.'UcApplication.php');  
Yii::createApplication('UcApplication', $config)->run();  